name = "website"                     # your project name
type = "javascript"
compatibility_date = "2025-05-01"

# === Required for Pages ===
pages_build_output_dir = "public"    # tells Pages where your static files live

# === (Optional) Environment variables ===
[vars]
JWKS_URI      = "https://login.microsoftonline.com/.../discovery/v2.0/keys"
AAD_CLIENT_ID = "your-client-id"
AAD_ISSUER    = "https://login.microsoftonline.com/.../v2.0"
