# wrangler.toml
name = "my-secure-app"
type = "javascript"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

# tell Pages where your static site is
pages_build_output_dir = "public"

