name: Build and deploy Azure Functions (Node.js)

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

env:
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install production dependencies
      run: |
        cd api
        npm ci --omit=dev
        
    - name: Zip functions
      run: |
        cd api
        zip -r ../functionapp.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: functionapp
        path: functionapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: functionapp

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Function App
      uses: Azure/functions-action@v1
      with:
        app-name: 'maanit-func'
        package: './functionapp.zip'
