name: Build & Deploy Node.js → App Service (maanit-web-api)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_RESOURCE_GROUP:  ${{ secrets.AZURE_RESOURCE_GROUP }}    # optional, if you use RG in your login scope
  AZURE_WEBAPP_NAME:     maanit-web-api
  NODE_VERSION:          '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.zip.outputs.zipfile }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install & Build
        run: |
          npm ci
          npm run build --if-present
          npm run test  --if-present

      - name: Zip for deploy
        id: zip
        run: |
          ZIP=webapp.zip
          zip -qr $ZIP . -x ".git/*" "node_modules/*"
          echo "::set-output name=zipfile::$ZIP"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-artifact
          path: ${{ steps.zip.outputs.zipfile }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.webapp-url }}
    permissions:
      id-token: write      # needed for OIDC
      contents: read       # for checkout/download-artifact

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: webapp-artifact

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          # you can optionally scope down to a single RG:
          # scope: /subscriptions/${{ env.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP }}

      - name: Deploy to App Service
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name:  ${{ env.AZURE_WEBAPP_NAME }}
          package:   ${{ needs.build.outputs.artifact-path }}
          slot-name: production    # omit if you don’t use slots
