name: Build and deploy Node.js app to Azure Web App - maanit-website

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test (API)
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./api

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_95586A3E75A3451AAED0ED0C0ECB647C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_50D60EE2E43F417994B7FF14BD107403 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8698955FFBD3495EA7A1431E4DE754AA }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'maanit-website'
          slot-name: 'Production'
          package: ./api
