name: Deploy to Azure Static Web App

# Trigger the workflow on push to main branch
# and on pull request events for the main branch
on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  # Optional: Allow manual workflow runs from GitHub UI
  workflow_dispatch:

# Environment variables available to all jobs and steps
env:
  APP_LOCATION: "/" # Location of your app code - this is the repository root
  API_LOCATION: "api" # Location of Azure Functions code
  OUTPUT_LOCATION: "build" # Location of build output for your app

# Set proper permissions for the GitHub token
permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_job:
    # Only run this job when it's not a pull request being closed
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      # Deploy to Azure Static Web Apps
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for PR comments
          action: "upload"
          # Deployment configurations
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          # Skip dependency detection to avoid lock file errors
          skip_app_build: false

  # This job closes the deployment for PRs that are closed
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Environment
    steps:
      - name: Close Pull Request Deployment
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"